// The control page, served from flash as one static asset.
//
// Dependency-free on purpose: no CDN, no framework, so it works on a bench
// network with no internet and opens from a phone standing next to the board.
//
// The shape is summary-first. The question you have when you open this page is
// "is it alive and how far along", so that is answered at the top in words and
// a bar; the bus trace, the retention scan and the board settings are folded
// away behind <details>, because you want them rarely and they were drowning
// the things you want constantly.
//
// TWO THINGS DELIBERATELY ABSENT:
//
//   - A single-step button. This is dynamic logic: bus_step_cycle() rests the
//     clock LOW, and the worst node holds charge for about 1.1 ms (measured,
//     board #1) in exactly that state. A human takes 200 ms to click. Stepping
//     twice does not resume the first step, it resumes decayed garbage that
//     merely looks like a machine. "Reset and run" replaces it, and is
//     deterministic because it always starts from reset.
//   - A stop-then-look workflow. The clock cannot pause while you read, so the
//     trace ring IS the debugger: capture a burst, then read the recording.
//     History does not decay.
#pragma once

static const char PAGE_HTML[] =
    "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nConnection: close\r\n\r\n"
    "<!doctype html><meta charset=utf-8>"
    "<meta name=viewport content='width=device-width,initial-scale=1'>"
    "<title>discrete6502</title><style>"
    ":root{--bg:#12161a;--card:#1a2027;--ink:#e8edf2;--dim:#8a96a3;--line:#28313b;"
    "--ok:#4ec98a;--bad:#e86a6a;--acc:#5aa9e6;"
    "--m:ui-monospace,SFMono-Regular,Menlo,monospace}"
    "*{box-sizing:border-box}"
    "body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 system-ui,"
    "-apple-system,Segoe UI,Roboto,sans-serif}"
    ".w{max-width:640px;margin:0 auto}"
    ".top{display:flex;justify-content:space-between;align-items:center;padding:14px 18px;"
    "border-bottom:1px solid var(--line)}"
    ".brand{font-weight:600}.host{font-family:var(--m);font-size:12px;color:var(--dim)}"
    ".body{padding:18px}"
    ".pill{display:inline-flex;align-items:center;gap:7px;font-size:13px;font-weight:600;"
    "padding:4px 11px 4px 9px;border-radius:99px}"
    ".pill i{width:8px;height:8px;border-radius:50%;display:block}"
    ".idle{background:rgba(138,150,163,.14);color:var(--dim)}.idle i{background:var(--dim)}"
    ".run{background:rgba(78,201,138,.14);color:var(--ok)}"
    ".run i{background:var(--ok);animation:b 1.6s ease-in-out infinite}"
    ".pass{background:rgba(78,201,138,.14);color:var(--ok)}.pass i{background:var(--ok)}"
    ".fail{background:rgba(232,106,106,.14);color:var(--bad)}.fail i{background:var(--bad)}"
    "@keyframes b{0%,100%{opacity:1}50%{opacity:.35}}"
    "@media(prefers-reduced-motion:reduce){.run i{animation:none}}"
    "h2{font-size:1.15rem;font-weight:500;margin:10px 0 2px}"
    ".sub{color:var(--dim);font-size:13.5px;margin:0 0 4px}"
    ".bar{height:7px;background:var(--line);border-radius:99px;overflow:hidden;margin:13px 0 7px}"
    ".bar i{display:block;height:0;height:100%;width:0;background:var(--ok);border-radius:99px;"
    "transition:width .5s}"
    ".figs{display:flex;gap:26px;margin-top:15px;padding-top:14px;border-top:1px solid var(--line)}"
    ".n{font-family:var(--m);font-size:19px;font-variant-numeric:tabular-nums;font-weight:500}"
    ".l{font-size:11px;color:var(--dim);letter-spacing:.07em;text-transform:uppercase;margin-top:3px}"
    ".acts{display:flex;gap:8px;flex-wrap:wrap;padding:15px 18px;border-top:1px solid var(--line);"
    "border-bottom:1px solid var(--line);background:rgba(0,0,0,.16)}"
    "button{font:inherit;font-size:14px;font-weight:500;padding:9px 16px;border-radius:7px;"
    "border:1px solid var(--line);background:var(--card);color:var(--ink);cursor:pointer}"
    "button:hover{border-color:var(--dim)}"
    "button:focus-visible{outline:2px solid var(--acc);outline-offset:2px}"
    "button.p{background:var(--ok);border-color:var(--ok);color:#0d1a13;font-weight:600}"
    "details{border-bottom:1px solid var(--line)}details:last-of-type{border-bottom:0}"
    "summary{padding:13px 18px;cursor:pointer;display:flex;align-items:center;gap:12px;"
    "list-style:none;font-size:14px}summary::-webkit-details-marker{display:none}"
    "summary:focus-visible{outline:2px solid var(--acc);outline-offset:-2px}"
    "summary::after{content:'\\203A';color:var(--dim);font-size:19px;line-height:1;"
    "transform:rotate(90deg);transition:transform .18s}"
    "details[open] summary::after{transform:rotate(-90deg)}"
    "@media(prefers-reduced-motion:reduce){summary::after{transition:none}}"
    ".hint{color:var(--dim);font-size:12.5px;margin-left:auto;text-align:right}"
    ".in{padding:2px 18px 18px}"
    ".kv{color:var(--dim);font-size:13.5px;margin:0 0 11px}"
    ".chips{display:flex;gap:7px;flex-wrap:wrap}"
    ".chip{font-size:13px;padding:6px 12px;border-radius:99px;border:1px solid var(--line);"
    "background:var(--card);color:var(--ink);cursor:pointer;font-family:var(--m)}"
    "#log,#con{font-family:var(--m);font-size:12.5px;line-height:1.7;background:rgba(0,0,0,.24);"
    "border-radius:7px;padding:11px 13px;max-height:180px;overflow:auto;white-space:pre-wrap}"
    "#con{min-height:52px}"
    ".g{color:var(--ok)}.warn{color:var(--acc)}.r{color:var(--bad)}.d{color:var(--dim)}"
    "table{width:100%;border-collapse:collapse;font-family:var(--m);font-size:12.5px;"
    "font-variant-numeric:tabular-nums}"
    "th{text-align:left;color:var(--dim);font-weight:400;font-size:11px;letter-spacing:.07em;"
    "text-transform:uppercase;padding:0 12px 6px 0}"
    "td{padding:2px 12px 2px 0;border-top:1px solid var(--line)}"
    ".sc{overflow-x:auto}"
    "input{font:inherit;background:var(--card);color:var(--ink);border:1px solid var(--line);"
    "border-radius:6px;padding:7px 9px;max-width:130px}"
    "</style>"

    "<div class=w>"
    "<div class=top><span class=brand>discrete6502</span><span class=host id=ip></span></div>"

    "<div class=body>"
    "<span class='pill idle' id=pill><i></i><span id=pillt>connecting</span></span>"
    "<h2 id=head>&nbsp;</h2><p class=sub id=sub></p>"
    "<div class=bar id=barw style=display:none><i id=bar></i></div>"
    "<p class=sub id=eta></p>"
    "<div class=figs>"
    "<div><div class=n id=fcyc>&mdash;</div><div class=l>cycles</div></div>"
    "<div><div class=n id=fhz>&mdash;</div><div class=l>clock</div></div>"
    "<div><div class=n id=fad>&mdash;</div><div class=l>address</div></div>"
    "</div></div>"

    "<div class=acts>"
    "<button class=p id=go onclick=primary()>Run</button>"
    "<button onclick=\"cmd('resetrun')\">Reset and run</button>"
    "<button onclick=\"cmd('run',200)\">Capture 200 cycles</button>"
    "</div>"

    "<details><summary>Program<span class=hint id=pgm></span></summary><div class=in>"
    "<p class=kv>Runs at power-up. Storing also stores the clock now set, so the runtime "
    "shown above is what the board will do unattended. It stops the CPU first and "
    "resets it afterwards \u2014 memory is live while the CPU runs, so a snapshot "
    "taken mid-run would capture a half-executed image.</p>"
    "<input type=file id=f><button onclick=up()>Upload hex</button> <span class=d id=ul></span>"
    "<div class=chips id=imgs style=margin-top:11px></div>"
    "<p class=kv id=imgw style='margin:10px 0 0;color:var(--bad);display:none'></p>"
    "<div class=chips style=margin-top:11px>"
    "<button class=chip onclick=\"if(confirm('Store the current memory as the boot image?'))"
    "cmd('store')\">Store as boot image</button>"
    "<button class=chip onclick=\"cmd('forget')\">Forget</button>"
    "<button class=chip onclick=\"cmd('vector')\">Vector &rarr; $0400</button>"
    "</div></div></details>"

    "<details><summary>Clock<span class=hint id=clk></span></summary><div class=in>"
    "<p class=kv>Measured window on board #1: floor about 871 Hz from charge retention, "
    "ceiling about 20 kHz from decode-PLA fanout.</p><div class=chips>"
    "<button class=chip onclick=\"cmd('clock',500)\">1 kHz</button>"
    "<button class=chip onclick=\"cmd('clock',167)\">3 kHz</button>"
    "<button class=chip onclick=\"cmd('clock',50)\">10 kHz</button>"
    "<button class=chip onclick=\"cmd('clock',25)\">20 kHz</button></div>"
    "<p class=kv style='margin:12px 0 0'>half-period "
    "<input type=number id=hp value=50 min=1> &micro;s "
    "<button onclick=\"cmd('clock',hp.value)\">Set</button>"
    "<button onclick=\"cmd('clocksave')\">Save</button></p>"
    "<p class=kv id=clksave style='margin:11px 0 0'></p></div></details>"

    "<details id=cond><summary>Console<span class=hint id=conh>off</span></summary>"
    "<div class=in>"
    "<p class=kv>$3F00 out &middot; $3F01 in (read it, then write to acknowledge) "
    "&middot; $3F02 status. Turn it off for the functional test: the suite checksums "
    "RAM up to $3FFF and these three addresses sit inside that.</p>"
    "<div id=con></div>"
    "<div class=chips style=margin-top:10px>"
    "<input id=ci placeholder='send to the CPU' style=max-width:260px>"
    "<button class=chip onclick=send()>Send</button>"
    "<button class=chip onclick=\"cmd('con',1)\">Console on</button>"
    "<button class=chip onclick=\"cmd('con',0)\">Off</button></div>"
    "</div></details>"

    "<details open><summary>Activity<span class=hint id=lh></span></summary>"
    "<div class=in><div id=log></div></div></details>"

    "<details><summary>Bus trace<span class=hint>the debugger on this machine</span></summary>"
    "<div class=in><p class=kv>The clock cannot pause while you read, so capture a burst and "
    "read the recording. History does not decay.</p>"
    "<div class=sc><table id=tr></table></div></div></details>"

    "<details><summary>Network<span class=hint id=neth></span></summary>"
    "<div class=in>"
    "<p class=kv>Reachable at <b id=nip>&mdash;</b>, and at <b>discrete6502.local</b> "
    "whichever address the router hands out. The link is watched: a drop is retried, "
    "and if it cannot be recovered the board falls back to its own setup access "
    "point rather than going quiet.</p>"
    "<p class=kv style='margin:12px 0 7px'>Forgetting the network reboots the board into "
    "setup mode. You will lose this page, and reach it again by joining "
    "<b>discrete6502-setup</b> and opening http://192.168.4.1/. The CPU keeps running "
    "throughout &mdash; only the way you talk to it changes.</p><div class=chips>"
    "<button class=chip onclick=\"if(confirm('Forget this network?\\n\\nThe board reboots "
    "into setup mode and this page will stop responding. To get back, join the "
    "discrete6502-setup network and open http://192.168.4.1/'))cmd('wifireset')\">"
    "Forget this network</button></div>"
    "</div></details>"

    "<details><summary>Diagnostics<span class=hint>retention &middot; watcher</span></summary>"
    "<div class=in>"
    "<p class=kv>Charge retention finds the clock's lower bound. It takes minutes and replaces "
    "the running program.</p><div class=chips>"
    "<button class=chip onclick=\"cmd('retscan',0)\">Find the clock floor</button>"
    "<button class=chip onclick=\"cmd('ret',rms.value)\">One stall</button>"
    "<button class=chip onclick=cmd('stop')>Stop</button></div>"
    "<p class=kv style='margin:11px 0 0'>stall <input type=number id=rms value=5 min=0> ms</p>"
    "<p class=kv style='margin:13px 0 7px'>Test watcher <span id=rst></span></p><div class=chips>"
    "<button class=chip onclick=\"cmd('ft',1)\">Watcher on</button>"
    "<button class=chip onclick=\"cmd('ft',0)\">Off</button></div>"
    "<p class=kv style='margin:13px 0 7px'>Clock the CPU at power-up "
    "<span id=arst></span> <span class=d>&mdash; an unclocked board draws more, "
    "not less</span></p><div class=chips>"
    "<button class=chip onclick=\"cmd('autorun',1)\">Autorun on</button>"
    "<button class=chip onclick=\"cmd('autorun',0)\">Off</button></div>"
    "</div></details>"
    "</div>"

    "<script>"
    "let last=-1,lastTrap=0,rseq=0,rv=0,news=0;"
    "const E=i=>document.getElementById(i);"
    "const hx=(n,w)=>n.toString(16).toUpperCase().padStart(w,'0');"
    "const dur=s=>s<90?s+' s':s<5400?Math.round(s/60)+' min':"
    "Math.floor(s/3600)+' h '+String(Math.round(s%3600/60)).padStart(2,'0')+' m';"
    "const L=(s,c)=>{const d=E('log'),t=new Date().toTimeString().slice(0,8);"
    "d.innerHTML+='<span class=d>'+t+'</span> <span class='+(c||'d')+'>'+s+'</span>\\n';"
    "d.scrollTop=1e9;news++;E('lh').textContent=news+' new'};"
    // warn was already being returned (the console's functional-test caution)
    // and nothing ever displayed it. A reply the UI silently drops is worse
    // than no reply, because the caller believes the command was unremarkable.
    "const cmd=(o,v)=>fetch('/cmd?op='+o+(v!==undefined?'&v='+v:''))"
    ".then(r=>r.json()).then(j=>{if(j.err)L(j.err,'r');if(j.warn)L(j.warn,'warn');poll()})"
    ".catch(()=>L('no reply &mdash; the board may be rebooting','warn'));"
    "function primary(){cmd(E('go').dataset.run=='1'?'stop':'run')}"
    "function up(){const f=E('f').files[0];if(!f)return;E('ul').textContent='uploading...';"
    "f.text().then(t=>fetch('/load',{method:'POST',body:t}).then(r=>r.json()).then(j=>{"
    "E('ul').textContent=j.err?j.err:(j.bytes+' bytes, vector $'+hx(j.vec,4));"
    "if(!j.err)L('Loaded '+j.bytes+' bytes','g')}))}"

    "function poll(){fetch('/status').then(r=>r.json()).then(j=>{"
    "E('ip').textContent=j.ip;E('nip').textContent=j.ip;E('neth').textContent=j.ip;"
    "const nm=j.pname||(j.img?'stored image':'counter loop');"
    // A finished run outranks a running one: the verdict is the answer you came
    // for. j.tk says whether the trap table knows this address; without
    // -DEMBED_FUNCTEST=ON it never does, and we report the bare address instead
    // of guessing at pass or fail.
    "let cls='idle',txt='Stopped';"
    "if(j.tr){cls=j.tk?(j.tp?'pass':'fail'):'fail';txt=j.tk?(j.tp?'Passed':'Failed'):'Halted'}"
    "else if(j.run){cls='run';txt='Running'}"
    "E('pill').className='pill '+cls;E('pillt').textContent=txt;"
    "E('go').dataset.run=j.run?'1':'0';E('go').textContent=j.run?'Stop':'Run';"

    "if(j.tr){"
    "E('head').textContent=nm+(j.tk?(j.tp?' complete':' stopped at a failure'):' halted');"
    "E('sub').innerHTML='Self-loop at $'+hx(j.ta,4)+(j.tk?"
    "(' &middot; listing line '+j.tl):"
    "' &middot; build with -DEMBED_FUNCTEST=ON to name it');"
    "E('barw').style.display='none';"
    "E('eta').textContent=j.cyc.toLocaleString()+' cycles';"
    "}else{"
    "E('head').textContent=nm;"
    "E('sub').innerHTML=j.ft?('Checkpoint $'+hx(j.tc,2)+' &middot; watcher on'):"
    "'Watcher off &mdash; no test progress is being tracked';"
    // Progress from cycles rather than checkpoints: exact, needs no checkpoint
    // table, and works for any image whose measured cycle count was stored.
    "if(j.tcyc&&j.run){const p=Math.min(100,100*j.cyc/j.tcyc);"
    "E('barw').style.display='';E('bar').style.width=p.toFixed(1)+'%';"
    "const left=Math.max(0,(j.tcyc-j.cyc)*2*j.half/1e6);"
    "E('eta').textContent='About '+dur(Math.round(left))+' remaining at this clock.';"
    "}else{E('barw').style.display='none';"
    "E('eta').textContent=j.secs?('About '+dur(j.secs)+' for a full run at this clock.'):''}}"

    "E('fcyc').textContent=j.cyc.toLocaleString();"
    "E('fhz').textContent=(1e6/(2*j.half)).toFixed(0)+' Hz';"
    "E('fad').textContent='$'+hx(j.a,4);"
    "E('pgm').textContent=j.img?(nm+' \\u00b7 '+j.img+' bytes'):'built-in counter';"
    "E('clk').textContent=(1e6/(2*j.half)).toFixed(0)+' Hz';"
    // Changing the clock does not write flash, because doing so would park the
    // bus engine and wipe the CPU's state. Show when live and saved differ.
    "E('clksave').innerHTML=j.half==j.shalf?"
    "('Saved as the power-up default.'):"
    "('Running at '+(1e6/(2*j.half)).toFixed(0)+' Hz, but the board still starts at '"
    "+(1e6/(2*j.shalf)).toFixed(0)+' Hz \\u2014 Save makes it the default. "
    "Saving resets the CPU: writing flash stops the clock for longer than the "
    "dynamic nodes hold charge.');"
    "E('rst').textContent=j.rb?'running...':(j.ft?'on':'off');"
    "E('arst').textContent=j.ar?'(on)':'(off)';"

    "if(j.ft&&j.tc!==last){if(last>=0)L('Checkpoint $'+hx(j.tc,2)+' at cycle '+j.cyc,'g');"
    "last=j.tc}"
    "if(j.tr&&!lastTrap){L(j.tk?((j.tp?'PASSED':'FAILED')+' at $'+hx(j.ta,4)+"
    "', listing line '+j.tl):('Self-loop at $'+hx(j.ta,4)+' after '+j.cyc+' cycles'),"
    "j.tk&&j.tp?'g':'r')}lastTrap=j.tr;"
    "if(j.rs>rseq){rseq=j.rs;L('Retention: '+j.rms+' ms \\u2192 '+(j.rok?'survived':'LOST'),"
    "j.rok?'g':'r')}if(j.rs<rseq)rseq=j.rs;"
    "if(j.rv!==rv){rv=j.rv;"
    "if(j.rv==1)L('Retention control failed: the CPU does not run even with no stall. "
    "Fix that before believing any number.','r');"
    "else if(j.rv==2)L('Retention boundary: survives '+j.rg+' ms, fails at '+j.rbad+' ms "
    "\\u2192 clock floor about '+(j.rg?Math.round(1000/j.rg):0)+' Hz','g');"
    "else if(j.rv==3)L('Still alive at the limit \\u2014 search higher','d');"
    "else if(j.rv==4)L('Retention scan stopped','d')}"
    "})}"

    // /trace emits arrays, not objects: [cycle, addr, data, flags] with flags
    // bit0 = read and bit1 = sync. Kept that way because it is a third the bytes
    // over a link this small.
    "function trace(){fetch('/trace?n=16').then(r=>r.json()).then(j=>{"
    "E('tr').innerHTML='<tr><th>cycle<th>address<th>data<th>r/w<th>sync'+j.t.map(e=>"
    "'<tr><td>'+e[0]+'<td>$'+hx(e[1],4)+'<td>'+hx(e[2],2)+'<td>'+((e[3]&1)?'read':'write')+"
    "'<td>'+((e[3]&2)?'\\u2022':'')).join('')})}"
    "function send(){const v=E('ci').value;if(!v)return;"
    "fetch('/con?send='+encodeURIComponent(v)).then(r=>r.json()).then(j=>{"
    "E('ci').value='';L('Sent '+j.queued+' chars to the CPU','d')})}"
    "E('ci').addEventListener('keydown',e=>{if(e.key=='Enter')send()});"
    // The CPU's output is drained on read, so this poll is the only consumer --
    // do not add a second one or they will each get half the characters.
    "function con(){fetch('/con').then(r=>r.json()).then(j=>{"
    "E('conh').textContent=j.on?(j.total+' chars'+(j.pending?', '+j.pending+' queued in':'')):'off';"
    "if(j.s){const d=E('con');d.textContent+=j.s;d.scrollTop=1e9;"
    "if(!E('cond').open)E('cond').open=true}})}"
    // Built-in images, listed once at load: they cannot change while running.
    "fetch('/images').then(r=>r.json()).then(j=>{"
    "E('imgs').innerHTML=j.l.map(i=>'<button class=chip onclick=\"loadimg(\\''+i.k+"
    "'\\','+i.w+')\">'+i.n+(i.s?' <span class=d>'+(i.s<5400?Math.round(i.s/60)+' min':"
    "Math.floor(i.s/3600)+' h '+String(Math.round(i.s%3600/60)).padStart(2,'0')+' m')"
    "+'</span>':'')+'</button>').join('')"
    "+(j.have?'':'<span class=d>the acceptance tests are not compiled in \\u2014 they are "
    "GPLv3, see gen/functest/README.md. Rebuild with -DEMBED_FUNCTEST=ON.</span>')});"
    // The warning belongs at load time, not after a wasted multi-hour run.
    "function loadimg(k,w){cmd('img&k='+k);E('imgw').style.display=w?'':'none';"
    "if(w)E('imgw').textContent='This image\\u2019s interrupt vector is live code, not a "
    "self-loop. Tie irq and nmi high at the bond pads before a long run \\u2014 neither has a "
    "pull-up on this board, and a spurious interrupt would be absorbed and reappear as a "
    "failure somewhere unrelated.'}"
    "poll();trace();con();setInterval(poll,500);setInterval(trace,1500);setInterval(con,600);"
    "</script>";
