// discrete6502 bus engine: the Pico 2 W as clock master + memory emulator.
//
// Pin map — MUST match the GPIO wiring generated by tools/gen_netlist.py
// (26 lines through the factory-fitted 1k series resistors):
//   GP0-7   db0-7    data bus (bidirectional)
//   GP8-21  ab0-13   address bus (input; 16 KB window, CPU sees it mirrored)
//   GP22    clk0     clock to the CPU (output; we are the clock master)
//   GP26    /res     reset (open-drain: drive low / float high, board pulls up)
//   GP27    r/w      1 = CPU reads, 0 = CPU writes (input)
//   GP28    sync     high during opcode fetch (input)
#pragma once
#include <stdbool.h>
#include <stdint.h>

#define PIN_DB0 0
#define PIN_AB0 8
#define PIN_CLK0 22
#define PIN_RES 26
#define PIN_RW 27
#define PIN_SYNC 28

#define DB_MASK (0xFFu << PIN_DB0)
#define AB_MASK (0x3FFFu << PIN_AB0)

#define BUS_MEM_SIZE 0x4000u  // 16 KB, CPU address & 0x3FFF
#define BUS_TRACE_LEN 1024u   // ring buffer of recent bus cycles

typedef struct {
    uint32_t cycle;
    uint16_t addr;   // 14-bit address as seen on ab0-13
    uint8_t data;
    uint8_t rw_read; // 1 = read cycle
    uint8_t sync;    // 1 = opcode fetch
} bus_trace_t;

// Memory-mapped IO hook: called before RAM for every access.
// Return true if handled (on reads, *data must be filled in).
typedef bool (*bus_io_fn)(uint16_t addr, bool is_write, uint8_t *data);

// Per-cycle observer, called after every completed bus cycle. Return false
// to make bus_run() / bus_step_instruction() stop early — that is how a
// watcher (see functest.h) aborts a multi-hour run the moment it sees
// something worth stopping for.
typedef bool (*bus_watch_fn)(const bus_trace_t *t);

// clk_open_drain: drive clk0 low actively but float it high. Pass FALSE.
// There is NO pull-up on clk0 on this board — it is a pure input (two FET
// gates, a 100R series resistor, clamp diodes), so nothing holds it high and
// open-drain leaves it floating, which a dynamic CPU cannot survive. True is
// usable only with an external 10k croc-clipped from the PHI0 bond pad to VCC.
// Push-pull drives 3.3 V highs into the 5 V core, which is safe: clk0 gates
// only two pull-downs and the internal phases are regenerated on-board at full
// VCC swing. See README "Logic levels".
void bus_init(bool clk_open_drain);

void bus_set_half_period_us(uint32_t us);  // default 50 (=> 10 kHz, see bus6502.c)

// Asymmetric phases: phi2 (clock HIGH) for high_us, phi1 (clock LOW) for low_us.
//
// This is a POWER lever, and a large one. cclk follows clk0 -- traced through
// the netlist: clk0 low parks cclk low and every one of the 32 cclk-gated
// precharge FETs is off; clk0 high turns them all on against whatever holds
// their bus low. So contention current flows almost entirely during the high
// phase, and the average scales with duty cycle.
//
// The two bounds are measured, not guessed:
//   high >= ~25 us   logic settling, sim/fanout_speed.sp (PLA lines drive up
//                    to 71 gates behind a 10k pull-up; ~7 us to flip the
//                    receiving stage, ~25 us to a comfortable level)
//   low  <= ~500 us  charge retention, measured on board #1 2026-08-24:
//                    1.9-2.3 nA/FET, worst node sb6 holds 1.13 ms. Half that
//                    for margin.
// 40 us high / 400 us low is ~2.3 kHz at 9% duty: roughly a tenth of the
// contention current, and short enough peaks that a few hundred uF of bulk
// across VCC/VSS can supply them (50 us at 2 A into 0.2 V droop = 500 uF).
void bus_set_phase_us(uint32_t high_us, uint32_t low_us);
uint32_t bus_get_high_us(void);
uint32_t bus_get_low_us(void);
void bus_set_io(bus_io_fn fn);
void bus_set_watch(bus_watch_fn fn);  // NULL to remove

void bus_reset_assert(void);   // /res low
void bus_reset_release(void);  // /res floats high
// Full reset ceremony: assert, clock a few cycles, release. The CPU then
// runs its 7-cycle reset sequence and fetches the vector at $FFFC/D
// (= offset 0x3FFC/D in the 16 KB image).
void bus_reset_sequence(void);

// One full clock cycle: phi1 (address out) + phi2 (data transfer).
// Serves memory/IO and appends to the trace ring.
bus_trace_t bus_step_cycle(void);

// Run n cycles; returns last trace entry. Stops early if the watcher says so.
bus_trace_t bus_run(uint32_t n);
// Run until the start of the next instruction (sync high), with a cycle cap.
bus_trace_t bus_step_instruction(uint32_t max_cycles);
// True if the last bus_run()/bus_step_instruction() was cut short by the watcher.
bool bus_aborted(void);

uint8_t *bus_mem(void);  // the 16 KB image
extern uint32_t bus_cycle_count;

// Trace ring access: entry 0 = oldest available, bus_trace_avail()-1 = newest.
uint32_t bus_trace_avail(void);
bus_trace_t bus_trace_get(uint32_t idx_from_oldest);
void bus_trace_clear(void);
