// discrete6502 bus engine: the Pico 2 W as clock master + memory emulator.
//
// Pin map — MUST match the GPIO wiring generated by tools/gen_netlist.py
// (26 lines through the factory-fitted 1k series resistors):
//   GP0-7   db0-7    data bus (bidirectional)
//   GP8-21  ab0-13   address bus (input; 16 KB window, CPU sees it mirrored)
//   GP22    clk0     clock to the CPU (output; we are the clock master)
//   GP26    /res     reset (open-drain: drive low / float high, board pulls up)
//   GP27    r/w      1 = CPU reads, 0 = CPU writes (input)
//   GP28    sync     high during opcode fetch (input)
#pragma once
#include <stdbool.h>
#include <stdint.h>

#define PIN_DB0 0
#define PIN_AB0 8
#define PIN_CLK0 22
#define PIN_RES 26
#define PIN_RW 27
#define PIN_SYNC 28

#define DB_MASK (0xFFu << PIN_DB0)
#define AB_MASK (0x3FFFu << PIN_AB0)

#define BUS_MEM_SIZE 0x4000u  // 16 KB, CPU address & 0x3FFF
#define BUS_TRACE_LEN 1024u   // ring buffer of recent bus cycles

typedef struct {
    uint32_t cycle;
    uint16_t addr;   // 14-bit address as seen on ab0-13
    uint8_t data;
    uint8_t rw_read; // 1 = read cycle
    uint8_t sync;    // 1 = opcode fetch
} bus_trace_t;

// Memory-mapped IO hook: called before RAM for every access.
// Return true if handled (on reads, *data must be filled in).
typedef bool (*bus_io_fn)(uint16_t addr, bool is_write, uint8_t *data);

// clk_open_drain: drive clk0 low actively but float it high (board pull-up
// to VCC gives a full-swing clock; slower edges). Push-pull drives 3.3 V
// highs — see README "Logic levels" before choosing.
void bus_init(bool clk_open_drain);

void bus_set_half_period_us(uint32_t us);  // default 50 (=> 10 kHz, see bus6502.c)
void bus_set_io(bus_io_fn fn);

void bus_reset_assert(void);   // /res low
void bus_reset_release(void);  // /res floats high
// Full reset ceremony: assert, clock a few cycles, release. The CPU then
// runs its 7-cycle reset sequence and fetches the vector at $FFFC/D
// (= offset 0x3FFC/D in the 16 KB image).
void bus_reset_sequence(void);

// One full clock cycle: phi1 (address out) + phi2 (data transfer).
// Serves memory/IO and appends to the trace ring.
bus_trace_t bus_step_cycle(void);

// Run n cycles; returns last trace entry.
bus_trace_t bus_run(uint32_t n);
// Run until the start of the next instruction (sync high), with a cycle cap.
bus_trace_t bus_step_instruction(uint32_t max_cycles);

uint8_t *bus_mem(void);  // the 16 KB image
extern uint32_t bus_cycle_count;

// Trace ring access: entry 0 = oldest available, bus_trace_avail()-1 = newest.
uint32_t bus_trace_avail(void);
bus_trace_t bus_trace_get(uint32_t idx_from_oldest);
void bus_trace_clear(void);
