#!/usr/bin/env python3
"""Emit the quick self-test as a C header the selftest firmware links in.

The image is built by `tools/quick_selftest.py` — one definition, so the
firmware, the wifi panel and the serial path all run the same 23 subtests and
share the same verdict rule (the address the CPU settles at).

This is OUR code, not Klaus Dormann's, so unlike the functional-test images it
carries no licence entanglement and can be compiled in unconditionally.

    python3 tools/gen_selftest_image.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import quick_selftest as qst  # noqa: E402

OUT = ROOT / "pico-controller/selftest/selftest_image.h"


def records():
    """Same records quick_selftest.image() writes, before Intel-hex encoding."""
    code = qst.build()
    recs = [(0x0200, code), (qst.PASS_ADDR, qst.JMP(qst.PASS_ADDR))]
    for i in range(1, len(qst.TESTS) + 2):
        a = qst.FAIL_BASE + 3 * (i - 1)
        recs.append((a, qst.JMP(a)))
    recs.append((0x0490, qst.LDAi(0x42) + qst.RTS))
    recs.append((0x0600, qst.JMP(0x0600)))
    recs.append((0x3FFA, [0x00, 0x06, 0x00, 0x02, 0x00, 0x06]))
    return recs, code


def main():
    recs, code = records()
    names = [t[0] for t in qst.TESTS] + ["JSR / RTS"]

    flat = []
    for addr, data in recs:
        flat.append((addr, bytes(data)))

    lines = [
        "// GENERATED by tools/gen_selftest_image.py — do not edit.",
        "// The quick self-test image (our own code, no third-party licence).",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define SELFTEST_PASS_ADDR 0x{qst.PASS_ADDR:04X}",
        f"#define SELFTEST_FAIL_BASE 0x{qst.FAIL_BASE:04X}",
        f"#define SELFTEST_INT_TRAP  0x0600",
        f"#define SELFTEST_NTESTS    {len(names)}",
        f"#define SELFTEST_CODE_LEN  {len(code)}",
        "",
        "typedef struct { uint16_t addr; uint16_t len; const uint8_t *data; } selftest_rec_t;",
        "",
    ]
    for i, (addr, data) in enumerate(flat):
        body = ", ".join(f"0x{b:02X}" for b in data)
        lines.append(f"static const uint8_t selftest_d{i}[] = {{ {body} }};")
    lines.append("")
    lines.append("static const selftest_rec_t SELFTEST_RECS[] = {")
    for i, (addr, data) in enumerate(flat):
        lines.append(f"    {{ 0x{addr:04X}, {len(data)}, selftest_d{i} }},")
    lines.append("};")
    lines.append(f"#define SELFTEST_NRECS {len(flat)}")
    lines.append("")
    lines.append("static const char *const SELFTEST_NAMES[] = {")
    for n in names:
        lines.append(f'    "{n}",')
    lines.append("};")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    total = sum(len(d) for _, d in flat)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(flat)} records, {total} bytes, "
          f"{len(names)} subtests")


if __name__ == "__main__":
    main()
